# Generated by Django 2.0.2 on 2018-03-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapydjoblog',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joblog', to='django_apscheduler.DjangoJob'),
        ),
    ]
