# Generated by Django 2.0.2 on 2018-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180307_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OaUsersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('oa_user_id', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_send_email', models.BooleanField(default=False)),
            ],
        ),
    ]
